### PR TITLE
Add iOS universal dylib

### PR DESCRIPTION
**Pull request by chinmaygarde**
* The name of the config file expected by the tooling is `flutter_service.yaml` instead of `config.yaml`.
* The iOS dylib was previously being pushed to https://pub.dartlang.org/packages/firebase_flutter but I have added that dylib to this package instead of consistency.

### CODE REVIEW

**Comment by chinmaygarde** [comment]
cc @collinjackson

**Comment by collinjackson** [comment]
This is not ideal because we're checking in a 30MB opaque binary into a repo that was previously only Dart files. Ideally we'd put the dylib into cloud storage instead. I think it's fine to merge this, but we should plan to rebase and squash it out of the history before we land it on https://github.com/firebase/firebase-dart

**Comment by chinmaygarde** [comment]
Yeah, I will move it to another bucket after the hackathon

**Comment by collinjackson** [comment]
lgtm

**Comment by chinmaygarde** [comment]
I dont have write access to this repo. Can you click merge please.

**Comment by collinjackson** [comment]
Done. Also fixed your access permissions

**Pull request merged**
